-- Hint: Start with project_staff as the base table.
-- Join to staff on staff_id to get staff.name and dept_id.
-- Join to projects on proj_id to get projects.title and another dept_id.
-- To get departments.dept_name, join departments on dept_id (but which one? staff or projects?).
-- Sketch: project_staff INNER JOIN staff ON ... INNER JOIN projects ON ... LEFT JOIN departments ON ...
-- What keys link them? Ask yourself: which entity is missing if not joined?
